<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Win_P_Switch</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>

	  <!-- 应用图标 -->
	  <ApplicationIcon>Win+P Switch.ico</ApplicationIcon>
	  <!-- 单文件打包设置 -->
	  <PublishSingleFile>true</PublishSingleFile>

	  <!-- 新增：作者/版权信息，会被写进 exe 的文件属性里 -->
	  <Authors>Stephen Tam</Authors>
	  <Company>HKIIT 2526</Company>
	  <Product>主机输出外接切换工具</Product>
	  <Copyright>Copyright © 2026 Stephen Tam. Licensed under the MIT License.</Copyright>
	  <Version>0.0.1</Version>
	  <AssemblyVersion>0.0.0.1</AssemblyVersion>
	  <FileVersion>0.0.0.1</FileVersion>
	  <Description>Win+P Switch 一个用于输出外接切换的小工具</Description>
	  
  </PropertyGroup>

</Project>